apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-dept2-config
data:
  REACT_APP_DBB: http://20.197.102.22:5003/,
  REACT_APP_DB_USER: http://20.198.154.19:5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fe-dept2
  name: fe-dept2-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-dept2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fe-dept2
    spec:
      containers:
      - image: fazzyaziz/finosys-fe-dept2:v2
        imagePullPolicy: Always
        name: fe-dept2
        envFrom:
        - configMapRef:
            name: fe-dept2-config
---
apiVersion: v1
kind: Service
metadata:
  name: fe-dept2
spec:
  selector:
    app: fe-dept2
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

