apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-user1
spec:
 accessModes:
 - ReadWriteMany
 capacity:
   storage: 1Gi
 hostPath:
   path: /tmp/pv-user1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-user1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
---
apiVersion: v1
kind: Pod
metadata:
  name: db-user1
  labels:
    app: db-user1
spec:
  volumes:
  - name: pv-user1
    persistentVolumeClaim:
      claimName: pvc-user1
  containers:
  - image: mongo
    name: container-user1
    command:
    - mongod
    - "--bind_ip"
    - "0.0.0.0"
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: pv-user1
      mountPath: /data/db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-user1
  name: db-user1
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: db-user1
---