apiVersion: apps/v1
kind: Deployment
metadata:
  name: finosys-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finosys-be
  template:
    metadata:
      labels:
        app: finosys-be
    spec:
      containers:
      - image: fazzyaziz/simple-express-app:v2
        name: container-be
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5006
---
apiVersion: v1
kind: Service
metadata:
  name: finosys-be-svc
spec:
  ports:
  - port: 5006
    targetPort: 5006
  selector:
    app: finosys-be
  type: LoadBalancer