apiVersion: v1
kind: ConfigMap
metadata:
  name: finosys-fe-config
data:
  REACT_APP_BE: http://10.111.50.49:5006,

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: finosys-fe
  name: finosys-fe-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finosys-fe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: finosys-fe
    spec:
      containers:
      - image: fazzyaziz/simple-react:v1
        imagePullPolicy: Always
        name: finosys-fe
        envFrom:
        - configMapRef:
            name: finosys-fe-config
---
apiVersion: v1
kind: Service
metadata:
  name: finosys-fe
spec:
  selector:
    app: finosys-fe
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

